[package]
name = "cross_scratch2"
version = "0.1.0"
authors = ["SKAJohanVenter <aventer@ska.ac.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.19"}
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
argh = "0.1"
tango-client = "0.2.3"
unicode-width = "0.1"
tui-tree-widget = "0.4.0"
log = "0.4.14"