[package]
name = "tango-controls-tui"
version = "0.0.1"
authors = ["Johan Venter <a.johan.venter@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = { version = "0.19"}
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
clap = "3.0.0-beta.2"
tango-client = "0.2.3"
unicode-width = "0.1"
tui-tree-widget = "0.4.0"
log = "0.4.14"
log4rs = "1.0.0"
uuid = { version = "0.8", features = ["v4"] }