[package]
name = "tango-controls-tui"
version = "0.0.3"
authors = ["Johan Venter <a.johan.venter@gmail.com>"]
edition = "2021"
repository = "https://github.com/SKAJohanVenter/tango-controls-tui"

[dependencies]
crossterm = "0.22.1"
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
tango-client = "0.4.1"
unicode-width = "0.1.9"
tui-tree-widget = "0.7.0"
log = "0.4.14"
log4rs = "1.0.0"
anyhow = "1.0.48"
clap = "2.33.3"

[features]
