FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH=/usr/local/lib

RUN apt-get clean && apt-get update && apt-get install --no-install-recommends -y git wget curl build-essential omniidl libomniorb4-dev libcos4-dev libomnithread4-dev libzmq3-dev python3
RUN apt-get install -y --reinstall ca-certificates

# latest cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3.tar.gz
RUN tar -xzvf cmake-3.20.3.tar.gz
RUN cd cmake-3.20.3 && /cmake-3.20.3/bootstrap && make -j$(nproc) && make install

# tango-idl
RUN git clone  https://gitlab.com/tango-controls/tango-idl /tango-idl
RUN mkdir /tango-idl/build && cd /tango-idl/build && cmake .. && make install

# cppTango
RUN git clone  https://gitlab.com/tango-controls/cppTango /cppTango
RUN mkdir /cppTango/build
RUN cd /cppTango/build && cmake .. && make -j$(nproc) && make install

ENV PKG_CONFIG_PATH=/cppTango/build

# Install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

ENV CARGO_TARGET_DIR=/my-target